name: provider_fruits
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.2


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
     - assets/images/apple.jpg
     - assets/images/banana.jpg
     - assets/images/fig.jpg
     - assets/images/grapefruit.jpg
     - assets/images/kiwifruit.jpg
     - assets/images/lemon.jpg
     - assets/images/mandarin.jpg
     - assets/images/mango.jpg
     - assets/images/peache.jpg
     - assets/images/pear.jpg
     - assets/images/pineapple.jpg
     - assets/images/watermelon.jpg


     - family: Arimo
       fonts:
         - asset: assets/fonts/Arimo-Regular.ttf

